version: '3'

services:
  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=golang
      - POSTGRES_PASSWORD=fpf2023
    volumes:
      - db-data1:/var/lib/postgresql/data

volumes:
  db-data1:
